/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./public/index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  safelist: [
    {
      pattern: /(text|bg)-(blue|indigo|gray|green|red|purple)-(400|500)/,
    },
    "bg-lavender",
    "bg-sage",
    "bg-grape",
    "bg-pink",
    "bg-banana",
    "bg-mandarin",
    "bg-peacock",
    "bg-graphite",
    "bg-blueberry",
    "bg-basil",
    "bg-tomato",
    "text-lavender",
    "text-sage",
    "text-grape",
    "text-pink",
    "text-banana",
    "text-mandarin",
    "text-peacock",
    "text-graphite",
    "text-blueberry",
    "text-basil",
    "text-tomato",
  ],
  theme: {
    extend: {
      gridTemplateColumns: {
        "1/5": "1fr 5fr",
      },
      colors: {
        lavender: "#a4bdfc",
        sage: "#7ae7bf",
        grape: "#dbadff",
        pink: "#ff887c",
        banana: "#fbd75b",
        mandarin: "#ffb878",
        peacock: "#46d6db",
        graphite: "#e1e1e1",
        blueberry: "#5484ed",
        basil: "#51b749",
        tomato: "#dc2127",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
